### ISSUE TITLE
stronka nie dziala

### ISSUE THREAD

**Issue by ghost** [BMoszczynski07/SENIORity#1]
pomocy stronka nie dziala

**Comment by BMoszczynski07** [comment]
Aby uruchomić projekt lokalnie należy najpierw sklonować repozytorium, używając komendy "git clone <adres repozytorium>". W celu uruchomienia web servera należy wejść do katalogu "client" i pobrać wszystkie dependencies za pomocą "npm install". Aby uruchomić projekt w wersji deweloperskiej proszę użyć komendy "npm run dev".
